### ISSUE TITLE
Can't hear anyone. It's only Beeping

### ISSUE THREAD

**Issue by Schwardo19462** [danini1705/esx_radio#1]
My Problem is i can't hear anyone. I active PTT and Always on and never does somebody hear me. Only the Beeping is working

**Comment by danini1705** [comment]
esx or vrp

**Comment by danini1705** [comment]
Which release do you have

**Comment by Schwardo19462** [comment]
The last one. 20 Days before. resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

**Comment by danini1705** [comment]
You have to download the release 1.2.1

**Comment by codibez** [comment]
Is there a way to make it so people do not have to hold down Y **and** their PTT key?

**Comment by ghost** [comment]
> Is there a way to make it so people do not have to hold down Y **and** their PTT key?


Lane 39 of client.lua should look like this.. (Imagine that 'G' is your ptt key)
 `if IsControlPressed(2, Keys["Y"]) and IsControlPressed(2, Keys["G"]) and GetLastInputMethod(2) and Busy == false and PlayerData.job.name ~= nil and PlayerData.job.name == "police" then`

And lane 46...
`elseif not IsControlPressed(2, Keys["Y"]) and not IsControlPressed(2, Keys["G"]) and GetLastInputMethod(2) and Busy == true and PlayerData.job.name ~= nil and PlayerData.job.name == "police" then`

As u can see the 2nd's conditions checked now are **G is pressed**
